// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSc4qSl75ERakVYoc7yH2hFmuYQmNBJQ',
    appId: '1:50171865202:web:55afa6e64f18f75e193aeb',
    messagingSenderId: '50171865202',
    projectId: 'codvation-f2abd',
    authDomain: 'codvation-f2abd.firebaseapp.com',
    storageBucket: 'codvation-f2abd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1I-L4nPjEwHLa-8o-eHEcujrVFORMYh8',
    appId: '1:50171865202:android:8af817818ec2dcab193aeb',
    messagingSenderId: '50171865202',
    projectId: 'codvation-f2abd',
    storageBucket: 'codvation-f2abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1dn144Er7_GgAdB7cvhJn3Xx_Mph8Ys',
    appId: '1:50171865202:ios:74f433c95bd29c2d193aeb',
    messagingSenderId: '50171865202',
    projectId: 'codvation-f2abd',
    storageBucket: 'codvation-f2abd.firebasestorage.app',
    androidClientId: '50171865202-2s331h1n3f8gtf5n72pk6kmuonb7a8dc.apps.googleusercontent.com',
    iosClientId: '50171865202-1tc3hr4t0rdrfidovimrp59en5f0jcdv.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.esoi',
  );

}